apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
spec:
  selector:
    matchLabels:
      app: netflix
  replicas: 1
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: nginx
        ports:
        - containerPort: 80